document.write(' <table style="width: 227px; text-align: left; margin-left: auto; margin-right: auto;" border="0" cellpadding="0" cellspacing="0"> ')
document.write(' <tbody><tr><td class="newsheader" style="text-align: left; height: 14px;"><a class="IntLayer" href="./cale_det.htm">&nbsp;CLASSIFICA CANNONIERI ')
document.write(' </a></td></tr><tr><TD bgColor=#FFFFFF height=8 width=1></TD></tr> ')
document.write(' <tr><td><iframe name="tag" border="0" frameborder="0" width="227" height="250" align="center" src="Marcatori/class_marcatori.php" target="_blank" scrolling="auto"> ')
document.write(' </iframe></td></tr></tbody></table> ')