document.write (" <table style='width: 150px; height: 70px;' border='0' cellpadding='2' cellspacing='2'> ")
document.write (" <tbody><tr><td style='height: 14px;' class='newsheader'>&nbsp;::&nbsp;"+NomeMenuExtra+" ")
document.write (" </td></tr><tr><td class='newscell'> ")
document.write (" <script type='text/javascript'>Menuextra()</scr" + "ipt> ")
document.write (" </td></tr></tbody></table> ")