document.write("<table border='0' cellpadding='2' cellspacing='2' width='228'><tbody><tr>")
document.write("<td class='newsheader' height='15px'>&nbsp;&nbsp;MENU RAPIDO</td></tr><tr><td class='newscell'>")
document.write(" <script type='text/javascript'> Menurapido() </scr" + "ipt> ")
document.write(" <script language='Javascript'> ")
document.write(" function menultimelink(){ ")
document.write(" if (document.menultime.link.value != '#') window.open (document.menultime.link.value) ")
document.write(" } ")
document.write("</scr" + "ipt> ")
document.write(" <form name='menultime'> ")
document.write("<select name='link' onChange='javascript:menultimelink()' style='font-family:verdana; font-size:10px;'>")
document.write("<option value='#'>Ultime dai Campi di A</option>")
document.write("<option value=''>----------------------</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Ascoli/'>Ascoli</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Cagliari/'>Cagliari</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Chievo/'>Chievo</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Empoli/'>Empoli</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Fiorentina/'>Fiorentina</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Inter/'>Inter</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Juventus/'>Juventus</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Lazio/'>Lazio</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Lecce/'>Lecce</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Livorno/'>Livorno</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Messina/'>Messina</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Milan/'>Milan</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Palermo/'>Palermo</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Parma/'>Parma</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Reggina/'>Reggina</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Roma/'>Roma</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Sampdoria/'>Sampdoria</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Siena/'>Siena</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Treviso/'>Treviso</option>")
document.write("<option value='http://www.gazzetta.it/Calcio/Squadre/Udinese/'>Udinese</option>")
document.write("</select></form>")
document.write("</td></tr></tbody></table>")